//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace new_Theatre
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        public int id_performance { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public Nullable<DateTime> Time { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> id_author { get; set; }
    
        public virtual Author Author { get; set; }

        public Performance()
        {

        }

        public Performance(string Title, DateTime time , int Cost)
        {
            this.Title = Title;
            this.Address = "Большая красная 7";
            this.Cost = Cost;
            this.id_author = 1;
            this.Time = time;
        }
    }
}
