//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace new_Theatre
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasedTickets
    {
        public int ID_tickets { get; set; }
        public string Place { get; set; }
        public int ID_user { get; set; }
        public int ID_performance { get; set; }
    
        public virtual Performance Performance { get; set; }
        public virtual Users Users { get; set; }
    }
}
